Switch and Shift/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Switch_and_Shift.Interface;
using Switch_and_Shift.Models;

namespace Switch_and_Shift.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICategories _categoryRepository;

        public CategoriesController(ApplicationDbContext context,ICategories categoryRepository)
        {
            _context = context;
            _categoryRepository = categoryRepository;
        }

        // GET: CATEGORIES
        public async Task<IActionResult> Index()
        {
            return View(await _categoryRepository.GetAllCategoriesAsync());
        }

        // GET: CATEGORIES/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Category =await  _categoryRepository.GetCategoryByIdAsync(id);
            if (Category == null)
            {
                return NotFound();
            }

            return View(Category);
        }

        // GET: CATEGORIES/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: CATEGORIES/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("categories_id,categories_name")] Categories categories)
        {
            if (ModelState.IsValid)
            {
                
                await _categoryRepository.AddCategoryAsync(categories); 
                return RedirectToAction(nameof(Index));
            }
            return View(categories);
        }

        // GET: CATEGORIES/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            //var category= await _context.Categories.FindAsync(id);
            var category = await  _categoryRepository.GetCategoryByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: CATEGORIES/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("categories_id,categories_name")] Categories categories)
        {
            if (id != categories.categories_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                   await  _categoryRepository.UpdateCategoryAsync(categories);                  
                }
                catch (DbUpdateConcurrencyException)
                {
                 
                    if (! await _categoryRepository.CategoryExistsAsync(categories.categories_id)) 
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categories);
        }

        // GET: CATEGORIES/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Category = await _categoryRepository.GetCategoryByIdAsync(id);
            if (Category == null)
            {
                return NotFound();
            }

            return View(Category);
        }

        // POST: CATEGORIES/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
          
            var Category = await _categoryRepository.GetCategoryByIdAsync(id);

            if (Category != null)
            {
                await _categoryRepository.DeleteCategoryAsync(id);
            }
            return RedirectToAction(nameof(Index));
        }

        private Task<bool> CategoryExists(int id)
        {
            return  _categoryRepository.CategoryExistsAsync(id);
        }
    }
}

Switch and Shift/Controllers/Reports_AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Switch_and_Shift.Interface;
using Switch_and_Shift.Models;
using Switch_and_Shift.Repository;

namespace Switch_and_Shift.Controllers
{
    public class Reports_AdminController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IReportsAdminRepository reportsAdminRepository;

        public Reports_AdminController(ApplicationDbContext context,IReportsAdminRepository reportsAdminRepository)
        {
            _context = context;
            this.reportsAdminRepository = reportsAdminRepository;
        }

        // GET: REPORTS_ADMIN
        public async Task<IActionResult> Index()
        {
            return View(await reportsAdminRepository.GetAllReportsAsync());
        }


        // GET: REPORTS_ADMIN/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

           
            var reports_admin = await reportsAdminRepository.GetReportByIdAsync(id);
            if (reports_admin == null)
            {
                return NotFound();
            }

            return View(reports_admin);
        }

        // GET: REPORTS_ADMIN/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: REPORTS_ADMIN/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Reports_Admin Report_Admin)
        {
            string email = HttpContext.Session.GetString("Admin_Email");
            
            if (ModelState.IsValid)
            {
              await  reportsAdminRepository.AddReportAsync(Report_Admin);
               return RedirectToAction(nameof(Index));
            }
            return View(Report_Admin);
        }

        // GET: REPORTS_ADMIN/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Report_Admin = await reportsAdminRepository.GetReportByIdAsync(id);
            if (Report_Admin == null)
            {
                return NotFound();
            }
            return View(Report_Admin);
        }


        [HttpGet]
        public async Task<IActionResult> ReportPost2(int? id)
        {
            if (id.HasValue)
            {
                
                var reports_admin = await reportsAdminRepository.GetReportByIdAsync(id);
                reports_admin.report_show = 0;
               await  reportsAdminRepository.UpdateReportAsync(reports_admin);
            }

            var visibleReports = await reportsAdminRepository.GetVisibleReportsAsync();
            return View(visibleReports);
        }



        // POST: REPORTS_ADMIN/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("report_admin_id,reporter_email,reportee_email")] Reports_Admin Report_Admin)
        {
            if (id != Report_Admin.report_admin_id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await reportsAdminRepository.UpdateReportAsync((Reports_Admin) Report_Admin);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    bool reports_adminExists = reportsAdminRepository.ReportExists(Report_Admin.report_admin_id);
                    if (!reports_adminExists)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(Report_Admin);
        }

        // GET: REPORTS_ADMIN/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            

            var Report_Admin = await reportsAdminRepository.GetReportByIdAsync(id);
            if (Report_Admin == null)
            {
                return NotFound();
            }

            return View(Report_Admin);
        }

        // POST: REPORTS_ADMIN/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Report_Admin = await reportsAdminRepository.GetReportByIdAsync(id);
            await  reportsAdminRepository.DeleteReportAsync(Report_Admin);
            return RedirectToAction(nameof(Index));
        }

        private bool REPORTS_ADMINExists(int id)
        {
            return reportsAdminRepository.ReportExists(id);
        }
    }
}

Switch and Shift/Views/Layouts/_AdminLayout.cshtml
@{
    ViewData["Title"] = "Index";
}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Posts</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Saira+Semi+Condensed:wght@300;400;500;600;700&family=Shadows+Into+Light&display=swap"
          rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Saira+Semi+Condensed:wght@300;400;500;600;700&family=Shadows+Into+Light&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap theme -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous" />
    <!--Icons-->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="~/css/admin_index.css" />
    <link rel="stylesheet" type="text/css" href="~/css/header.css" />
    <link rel="stylesheet" href="css/category.css" />
    <link rel="stylesheet" href="css/category_button.css" />
</head>
<body>
    <header>
        <div class="bs-example">
            <div class="topnav">
                <nav class="navbar navbar-expand-md navbar-light bg-light">
                    <img class="logo_image" />
                    <div class="topnav-right user">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a asp-controller="Admin" class="nav-link dropdown-toggle" data-toggle="dropdown">
                                    <img src="~/website_images/profile_user_blue.png">
                                </a>
                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item">ADMIN</a>
                                    <div class="dropdown-divider"></div>
                                    <a asp-area="" asp-controller="Home" asp-action="Index" class="dropdown-item logout" id="log-out">Log Out</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="topnav-right"><a asp-controller="Admin" class="user_name">ADMIN</a></div>
                </nav>
            </div>
        </div>


        <nav class="navbar navbar-expand-md navbar-custom ">
            <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto ml-auto mx-auto">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Admin" asp-action="Index">USER LIST</a>
                    </li>
                    <a asp-controller="Categories" asp-action="Index" class="nav-link">Create Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Reports_Admin" asp-action="ReportPost2">Reports</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div>
        @RenderBody()
    </div>

    @RenderSection("Scripts", required: false)
</body>
</html>